- name: Copy elasticsearch repo
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install ELK
  ansible.builtin.dnf:
    name:
      - elasticsearch
      - kibana
      - logstash
      - nginx
    state: installed

- name: Copy nginx config file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Start ELK
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - elasticsearch
    - kibana
    - logstash
    - nginx

- name: Copy logstash config
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart Logstash
  ansible.builtin.systemd_service:
    name: logstash
    state: restarted

## Manual commands

# 1. Enrollment token for kibana
# /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana

# 2. Get OPT for kibana
# /usr/share/kibana/bin/kibana-verification-code

# 3. Reset elastic password
# /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic


